### ISSUE TITLE
SeperateItemInfo

### ISSUE THREAD

**Issue by cold-hr** [dastgir/Scripts#7]
SeperateItemInfo   has shuffled the item order

**Comment by dastgir** [comment]
Fixed in some commit: Probably https://github.com/dastgir/Scripts/commit/5a75b8a9e61c62cb61d6ff205303817ba13b8c65 or https://github.com/dastgir/Scripts/commit/3169b37735eb9708a1a4b0f766dc48ae5b3d3aee
